parameters:
    app_bundle.packageName: SpotifyPublicAPI
    app_bundle.metadata:
        package: "%app_bundle.packageName%"
        tagline: Spotify Public API Wrapper
        description: This package offers a variety of blocks by Spotify that do not require any authentication.
        image: https://developer.spotify.com/wp-content/uploads/2016/07/icon1@2x.png
        keywords:
          - API
          - album
          - albums
          - artist 
          - artists 
          - band 
          - music 
          - musician 
          - playlist 
          - playlists
          - song
          - songs
          - tracks
        repo: https://github.com/RapidSoftwareSolutions/Marketplace-SpotifyPublicAPI-Package
        blocks:
        -
          name: searchAlbums
          description: Search an album
          args:
            -
              name: query
              type: String
              info: "The search query's keywords (and optional field filters and operators)."
              required: true
            -
              name: market
              type: String
              info: "An ISO 3166-1 alpha-2 country code or the string from_token."
              required: false
            -
              name: limit
              type: String
              info: "The maximum number of results to return. Default: 20. Minimum: 1. Maximum: 50."
              required: false
            -
              name: offset
              type: String
              info: "The index of the first result to return. Default: 0 (i.e., the first result). Maximum offset: 100.000. Use with limit to get the next page of search results. "
              required: false
          callbacks:
            -
              name: error
              info: "error"
            -
              name: success
              info: "success"
        -
          name: searchArtists
          description: Search an artist
          args:
          args:
            -
              name: query
              type: String
              info: "The search query's keywords (and optional field filters and operators)."
              required: true
            -
              name: market
              type: String
              info: "An ISO 3166-1 alpha-2 country code or the string from_token."
              required: false
            -
              name: limit
              type: String
              info: "The maximum number of results to return. Default: 20. Minimum: 1. Maximum: 50."
              required: false
            -
              name: offset
              type: String
              info: "The index of the first result to return. Default: 0 (i.e., the first result). Maximum offset: 100.000. Use with limit to get the next page of search results. "
              required: false
          callbacks:
            -
              name: error
              info: "error"
            -
              name: success
              info: "success"
        -
          name: searchPlaylists
          description: Search a playlist
          args:
            -
              name: query
              type: String
              info: "The search query's keywords (and optional field filters and operators)."
              required: true
            -
              name: market
              type: String
              info: "An ISO 3166-1 alpha-2 country code or the string from_token."
              required: false
            -
              name: limit
              type: String
              info: "The maximum number of results to return. Default: 20. Minimum: 1. Maximum: 50."
              required: false
            -
              name: offset
              type: String
              info: "The index of the first result to return. Default: 0 (i.e., the first result). Maximum offset: 100.000. Use with limit to get the next page of search results. "
              required: false
          callbacks:
            -
              name: error
              info: "error"
            -
              name: success
              info: "success"
        -
          name: searchTracks
          description: Search tracks
          args:
            -
              name: query
              type: String
              info: "The search query's keywords (and optional field filters and operators)."
              required: true
            -
              name: market
              type: String
              info: "An ISO 3166-1 alpha-2 country code or the string from_token."
              required: false
            -
              name: limit
              type: String
              info: "The maximum number of results to return. Default: 20. Minimum: 1. Maximum: 50."
              required: false
            -
              name: offset
              type: String
              info: "The index of the first result to return. Default: 0 (i.e., the first result). Maximum offset: 100.000. Use with limit to get the next page of search results. "
              required: false
          callbacks:
            -
              name: error
              info: "error"
            -
              name: success
              info: "success"
        -
          name: getAlbum
          description: Get an album
          args:
            -
              name: id
              type: String
              info: "The Spotify ID for the album."
              required: true
          callbacks:
            -
              name: error
              info: "error"
            -
              name: success
              info: "success"
        -
          name: getAlbumTracks
          description: Get an album tracks
          args:
            -
              name: id
              type: String
              info: "The Spotify ID for the track."
              required: true
          callbacks:
            -
              name: error
              info: "error"
            -
              name: success
              info: "success"
        -
          name: getArtist
          description: Get an artist
          args:
            -
              name: id
              type: String
              info: "The Spotify ID for the artist."
              required: true
          callbacks:
            -
              name: error
              info: "error"
            -
              name: success
              info: "success"
        -
          name: getArtistAlbums
          description: Get artist albums
          args:
            -
              name: id
              type: String
              info: "The Spotify ID for the artist."
              required: true
            -
              name: album_type
              type: String
              info: "A comma-separated list of keywords that will be used to filter the response. If not supplied, all album types will be returned. Valid values are:album, single, appears_on, compilation."
              required: false
            -
              name: market
              type: String
              info: "An ISO 3166-1 alpha-2 country code. Supply this parameter to limit the response to one particular geographical market."
              required: false
            -
              name: limit
              type: String
              info: "The number of album objects to return. Default: 20. Minimum: 1. Maximum: 50."
              required: false
            -
              name: offset
              type: String
              info: "The index of the first album to return. Default: 0 (i.e., the first album). Use with limit to get the next set of albums. "
              required: false
          callbacks:
            -
              name: error
              info: "error"
            -
              name: success
              info: "success"
        -
          name: getArtistTopTracks
          description: Get artists top tracks
          args:
            -
              name: id
              type: String
              info: "The Spotify ID for the artist."
              required: true
            -
              name: country
              type: String
              info: "The country: an ISO 3166-1 alpha-2 country code."
              required: true
          callbacks:
            -
              name: error
              info: "error"
            -
              name: success
              info: "success"
        -
          name: getArtistRelatedArtists
          description: Get artist related artists
          args:
            -
              name: id
              type: String
              info: "The Spotify ID for the artist."
              required: true
          callbacks:
            -
              name: error
              info: "error"
            -
              name: success
              info: "success"
        -
          name: getTrack
          description: Get track
          args:
            -
              name: id
              type: String
              info: "The Spotify ID for the track."
              required: true
          callbacks:
            -
              name: error
              info: "error"
            -
              name: success
              info: "success"
        -
          name: getUserProfile
          description: Get user profile
          args:
            -
              name: id
              type: String
              info: "The Spotify ID for the user profile."
              required: true
          callbacks:
            -
              name: error
              info: "error"
            -
              name: success
              info: "success"

    app_bundle.spotifyUrl: "https://api.spotify.com/v1/"
    app_bundle.default_profile: "/"
    app_bundle.search_albums:
      url: "%app_bundle.spotifyUrl%"
      uri: "search?type=album&"
      method: "get"
      args_in_body: false
      limit_field_stop_pagination: true
      pagination_next_url_key: "next"
      object: false
      callback_message:
        error: "error"
        success: "success"
      args:
        q: "query"
        market: "market"
        limit: "limit"
        offset: "offset"
    app_bundle.search_artists:
      url: "%app_bundle.spotifyUrl%"
      uri: "search?type=artist&"
      method: "get"
      args_in_body: false
      limit_field_stop_pagination: true
      pagination_next_url_key: "next"
      object: false
      callback_message:
        error: "error"
        success: "success"
      args:
        q: "query"
        market: "market"
        limit: "limit"
        offset: "offset"
    app_bundle.search_playlists:
      url: "%app_bundle.spotifyUrl%"
      uri: "search?type=playlist&"
      method: "get"
      args_in_body: false
      limit_field_stop_pagination: true
      pagination_next_url_key: "next"
      object: false
      callback_message:
        error: "error"
        success: "success"
      args:
        q: "query"
        market: "market"
        limit: "limit"
        offset: "offset"
    app_bundle.search_tracks:
      url: "%app_bundle.spotifyUrl%"
      uri: "search?type=track&"
      method: "get"
      args_in_body: false
      limit_field_stop_pagination: true
      pagination_next_url_key: "next"
      object: false
      callback_message:
        error: "error"
        success: "success"
      args:
        q: "query"
        market: "market"
        limit: "limit"
        offset: "offset"
    app_bundle.get_album:
      url: "%app_bundle.spotifyUrl%"
      uri: "albums/:id"
      method: "get"
      args_in_body: false
      limit_field_stop_pagination: false
      pagination_next_url_key: "next"
      object:
        ":id": "id"
      callback_message:
        error: "error"
        success: "success"
      args: false
    app_bundle.get_album_tracks:
      url: "%app_bundle.spotifyUrl%"
      uri: "albums/:id/tracks"
      method: "get"
      args_in_body: false
      limit_field_stop_pagination: false
      pagination_next_url_key: "next"
      object:
        ":id": "id"
      callback_message:
        error: "error"
        success: "success"
      args: false
    app_bundle.get_artist:
      url: "%app_bundle.spotifyUrl%"
      uri: "artists/:id"
      method: "get"
      args_in_body: false
      limit_field_stop_pagination: false
      pagination_next_url_key: "next"
      object:
        ":id": "id"
      callback_message:
        error: "error"
        success: "success"
      args: false
    app_bundle.get_artist_albums:
      url: "%app_bundle.spotifyUrl%"
      uri: "artists/:id/albums?"
      method: "get"
      args_in_body: false
      limit_field_stop_pagination: true
      pagination_next_url_key: "next"
      object:
        ":id": "id"
      callback_message:
        error: "error"
        success: "success"
      args:
        album_type: "album_type"
        market: "market"
        limit: "limit"
        offset: "offset"
    app_bundle.get_artist_top_tracks:
      url: "%app_bundle.spotifyUrl%"
      uri: "artists/:id/top-tracks?"
      method: "get"
      args_in_body: false
      limit_field_stop_pagination: false
      pagination_next_url_key: "next"
      object:
        ":id": "id"
      callback_message:
        error: "error"
        success: "success"
      args:
        country: "country"
    app_bundle.get_artist_related_artists:
      url: "%app_bundle.spotifyUrl%"
      uri: "artists/:id/related-artists"
      method: "get"
      args_in_body: false
      limit_field_stop_pagination: false
      pagination_next_url_key: "next"
      object:
        ":id": "id"
      callback_message:
        error: "error"
        success: "success"
      args: false
    app_bundle.get_track:
      url: "%app_bundle.spotifyUrl%"
      uri: "tracks/:id"
      method: "get"
      args_in_body: false
      limit_field_stop_pagination: false
      pagination_next_url_key: "next"
      object:
        ":id": "id"
      callback_message:
        error: "error"
        success: "success"
      args: false
    app_bundle.get_user_profile:
      url: "%app_bundle.spotifyUrl%"
      uri: "users/:id"
      method: "get"
      args_in_body: false
      limit_field_stop_pagination: false
      pagination_next_url_key: "next"
      object:
        ":id": "id"
      callback_message:
        error: "error"
        success: "success"
      args: false

services:
    app_bundle.package_abstract:
        class: SpotifyPublicAPIBundle\Utils\ApiFunctions\Abstracts\SpotifyAbstract
        abstract: true
        arguments: ["@request_stack", "@buzz", "@app_bundle.query_builder", "@app_bundle.finder"]
    app_bundle.search_functions:
        class: SpotifyPublicAPIBundle\Utils\ApiFunctions\SearchFunctions
        parent: app_bundle.package_abstract
    app_bundle.get_functions:
        class: SpotifyPublicAPIBundle\Utils\ApiFunctions\GetFunctions
        parent: app_bundle.package_abstract
    app_bundle.finder:
        class: SpotifyPublicAPIBundle\Utils\ExtraFunctions\Finder
    app_bundle.query_builder:
        class: SpotifyPublicAPIBundle\Utils\ExtraFunctions\QueryBuilder
